CREATE DATABASE pos;

USE pos;

CREATE TABLE customers (
	id INT(111) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	address1 VARCHAR(50),
	address2 VARCHAR(20),
	city VARCHAR(20),
	state VARCHAR(2),
	zip_code INT(5),
	phone_number BIGINT(10) NOT NULL,
	email VARCHAR (50) NOT NULL DEFAULT "Declined",
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE employees (
	id INT(111) AUTO_INCREMENT NOT NULL,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	address1 VARCHAR(50) NOT NULL,
	address2 VARCHAR(20),
	city VARCHAR(20) NOT NULL,
	state VARCHAR(2) NOT NULL,
	zip_code INT(5)NOT NULL,
	phone_number BIGINT(10) NOT NULL,
	email VARCHAR(0) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	reports_to_employee_id INT(111),
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PRIMARY KEY(id),
	CONSTRAINT reports_to_employee_id FOREIGN KEY (reports_to_employee_id) 
		REFERENCES employees(id));

CREATE TABLE departments (
	id INT(111) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`name` VARCHAR(20) NOT NULL DEFAULT "Need Department Name",
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP());
	
CREATE TABLE vendors (
	id INT(111) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`name` VARCHAR(20) NOT NULL,
	address1 VARCHAR(50),
	address2 VARCHAR(20),
	city VARCHAR(20),
	state VARCHAR(2),
	zip_code INT(5),
	phone_number BIGINT(10) NOT NULL,
	rep_first_name VARCHAR(10) NOT NULL,
	rep_last_lame VARCHAR(20) NOT NULL,
	rep_email VARCHAR (50) NOT NULL,
	rep_phone_number BIGINT(10) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE items (
	id INT(111) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`name` VARCHAR(25) NOT NULL,
	description VARCHAR(255) NOT NULL DEFAULT "Description Needed",
	price DECIMAL(10, 2) NOT NULL,
	cost DECIMAL(10, 2) NOT NULL,
	department_id INT(111) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY(department_id)
		REFERENCES departments(id));
	
CREATE TABLE transactions (
	id INT(111) AUTO_INCREMENT NOT NULL,
	customer_id INT(111),
	employee_id INT(111) NOT NULL,
	payment ENUM ('CASH', 'CHECK', 'CREDIT'),
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id),
	FOREIGN KEY(customer_id)
		REFERENCES customers(id),
	FOREIGN KEY(employee_id)
		REFERENCES employees(id));
	
CREATE TABLE transaction_details (
	id INT(111) NOT NULL,
	item_id INT(111) NOT NULL,
	transaction_id INT(111) NOT NULL,
	quantity INT(11) NOT NULL CHECK(quantity > 0),
	PRIMARY KEY(id),
	FOREIGN KEY(transaction_id)
		REFERENCES transactions(id),
	FOREIGN KEY(item_id)
		REFERENCES items(id));